# Input topics handled/muxed.
# For each topic:
# - name    : name identifier to select the topic (*sub-namespace, see below)
# - topic   : input topic of geometry_msgs::Twist type
# - timeout : timeout in seconds to start discarding old messages, and use 0.0 speed instead
# - priority: priority in the range [0, 255]; the higher the more priority over other topics

twist_mux:
  ros__parameters:
    use_stamped: true
    topics:
      teleop:
        topic   : cmd_vel_joy_stamped
        timeout : 0.2
        priority: 100
      navigation:
        topic   : cmd_vel
        timeout : 0.5
        priority: 50
      keyboard:
        topic   : cmd_vel_keyboard_stamped
        timeout : 0.5
        priority: 40
